import { Base } from "@/components/Base";
import StyledComponentsRegistry from "@/lib/registry";
import { Providers } from "@/providers";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <StyledComponentsRegistry>
        <Providers>
          <body className={poppins.className}>
            <Base>{children}</Base>
          </body>
        </Providers>
      </StyledComponentsRegistry>
    </html>
  );
}
